### ISSUE TITLE
Feat: Allowing users to read blogs in different languauges

### ISSUE THREAD

**Issue by prakharsingh-74** [Suchitra-Sahoo/AgriLearnNetwork#210]
### Describe the feature

This feature helps the website to target the user all over the world which will help to increase in the website traffic.

### Add ScreenShots

adding more languages

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prakharsingh-74** [comment]
@Suchitra-Sahoo assign this issue to me as soon as possible

**Comment by somaakash** [comment]
@Suchitra-Sahoo 

I want to add more agro blogs such as

1)7 tips to get the best Wheat produce
2)All you need to know about grape farming in India
3)Food Transparency: Meeting Consumer Demands by Enhancing Ingredient Labels with Traceable Insights into Food Production 
(if possible i will try to try to put other good blogs if i came across any)

can u assign this small issue?
I am beginner to open source and i know web development ,
if possible i would like collaborate with @prakharsingh-74 so that blog section look good..

can u assign this small issue?

**Comment by Suchitra-Sahoo** [comment]
@prakharsingh-74 how will you implement it?

**Comment by prakharsingh-74** [comment]
@Suchitra-Sahoo by using html css and js
