### ISSUE TITLE
Feat: Change the font style 

### ISSUE THREAD

**Issue by riffhi** [Suchitra-Sahoo/AgriLearnNetwork#435]
### Describe the feature

I woud like to change the fonr style to something more simplistic and professional

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111896909/ce5defc9-857e-4a02-8096-ffe50f7c7079)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ParthNakum21** [comment]
Hello @Suchitra-Sahoo, I'm interested in contributing to the project by enhancing project's visual appeal by improving font styling. Could you please assign this task to me under GSSoC'24 with appropriate level?

**Comment by aakanksha-singh-hub** [comment]
Hi @Suchitra-Sahoo 

I hope you are doing well.

My name is Aakanksha Singh, and I am a participant in the Girlscript Summer of Code 2024. I am very interested in working on this issue because it aligns with my interests in frontend development, and would make this project more visually appealing.

Could you please assign this issue to me? I am confident that I can address it.

Thank you for considering my request. I look forward to contributing to this project.

**Comment by Mansi-Raj** [comment]
Hello @Suchitra-Sahoo 
I'm interested to contribute in this issue because this is the field of my interest. So, please assign this to me.
Thank you

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
