### ISSUE TITLE
Header section ( Home )

### ISSUE THREAD

**Issue by nisargaa20** [Suchitra-Sahoo/AgriLearnNetwork#52]
Home section is in bold compared to others and not able to hover that word 

kindly assign me this issue . I will work on it #gssoc24

![Uploading AgriLearnNetwork - Google Chrome 10-05-2024 17_56_51.png…]()

**Comment by Satyaas1117** [comment]
My ideas are:
1. I can change the hover effect in header section and aligning them for more effectiveness.
2.  Font size should be more understandable and i can change it as it is too bold that can create confusion for the user
3. I can add some icons to the header part.
please assign it to me so that i can work on these issues under GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
@nisargaa20 assigned. You may start working on it.

**Comment by nisargaa20** [comment]
@Suchitra-Sahoo Thank you so much . I will work on it

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Suchitra-Sahoo

**Comment by nisargaa20** [comment]
@Suchitra-Sahoo I have done the PR please check it out
