### ISSUE TITLE
BUG: After login refer to homepage

### ISSUE THREAD

**Issue by gungunjain15** [Suchitra-Sahoo/AgriLearnNetwork#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Homepage is not redirected after login 
@Suchitra-Sahoo Ma'am please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kushagrasaxena061** [comment]
@Suchitra-Sahoo Please assign this issue to me

**Comment by Suchitra-Sahoo** [comment]
add footer and navbar to login page and each option of navbar should redirect properly

**Comment by gungunjain15** [comment]
@Suchitra-Sahoo Ma'am please also add level label

**Comment by vaishnavi-jais** [comment]
Hi 

It seems our login process has hit a snag—after logging in, users are left hanging instead of being redirected to the homepage. It's like reaching the end of a journey and finding no destination!

I’m eager to fix this navigation hiccup and ensure users are seamlessly whisked away to the homepage after a successful login. Could you please assign me this task for GSoC '24? I’m ready to get this redirect issue sorted and enhance the user experience!

Thanks a bunch for considering my request!
